Crud therapy
iuresti/codegym-fisioapp pull request #20
Opened 2024-06-25 17:13 UTC by matahj

Complete CRUD of therapies, with error responses and timing.
The default value "pageIndex=1" was changed to "pageIndex=0".

2024-06-26 16:07 UTC, iuresti requested changes

2024-06-26 16:07 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/controller/TherapyController.java
> +        logger.info("createTherapy completed successfully in {} ms: {}", System.currentTimeMillis() - startTime, result.toString());
toString() of result object will be called automatically, IntelliJ should be warnng you about the redundant call to "toString"

I saw you're using it in several places, please remove all

2024-06-26 16:07 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/service/TherapyService.java
> +    TherapyDto createTherapy(TherapyDto terapyDto);
For readability, I recommend to add spaces between each method (a line).

2024-06-26 16:07 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/service/impl/TherapyServiceImpl.java
> +        if (all) {
Instead of line 98 the common practice is here in the if statement:
``` 
if(Boolean.TRUE.equals(all))
```
Same with line 99 and if in 109

2024-06-26 16:07 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/service/impl/TherapyServiceImpl.java
> +            return therapyRepository.findAllByActive(true, pageable).stream()
No need to change if you prefer this way but I'd prefer to get the list of Therapies from the repository and at the end one single return statement with the conversion: 
```
return therapiesList.stream()
                    .map(TherapyServiceImpl::convertTherapyToDto)
                    .collect(Collectors.toList());
```
This way you avoid the duplicated code.

2024-06-26 19:24 UTC, Davidmetam submitted a review, later dismissed

2024-06-27 15:56 UTC, iuresti approved these changes

2024-06-27 19:22 UTC, merged