crear Therapist con peticion POST
iuresti/codegym-fisioapp pull request #26
Opened 2024-06-29 04:50 UTC by JossMex

2024-06-30 00:30 UTC, iuresti requested changes

2024-06-30 00:30 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/dto/TherapistDto.java
> +    private Long id;
id should be a String as we are using UUID for this

2024-06-30 00:30 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/model/Therapist.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
We are not using auto-generated ids, please use UUID and set it from the service

2024-06-30 00:30 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/service/impl/TherapistServiceImpl.java
> +    public TherapistServiceImpl(TherapistRepository therapistRepository) {
separate declarations from methods with an empty line for readability

2024-06-30 00:30 UTC, iuresti commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/fisioapp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
don't change common settings unless you're adding new parameters or the change was an agreement by the team.

If you need to change the configuration define locally the parameter (you can pass via application arguments the parameter you need)

2024-06-30 00:30 UTC, iuresti commented on src/main/resources/init.sql
> +id BIGINT AUTO_INCREMENT PRIMARY KEY,
I recommend to autoformat this block of code, you'll see the columns will be idented and that's important for readability

2024-06-30 00:30 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/controller/TherapistController.java
> +@RestController
Auto format this file please and use "optimize imports" both options from the menu "Code" in intelliJ

2024-06-30 00:30 UTC, iuresti commented on src/main/java/codegym/tequila/fisioapp/controller/TherapistController.java
> +    public List<TherapistDto> getTherapists() {
Instead of a list return please a `Page<TherapistDto>` and define the parameters pageSize and pageIndex as query parameters

2024-07-04 16:59 UTC, iuresti requested changes
Perfect! only add unit tests please so we can proceed approving the PR

2024-07-11 06:16 UTC, Davidmetam submitted a review, later dismissed

2024-07-15 16:22 UTC, iuresti approved these changes

2024-07-15 22:00 UTC, merged